// clear-ledger-web/src/components/join-ledger-dialogue/index.tsx
import { AxiosError } from "axios"
import { Button, Form, Input, message, Modal } from "antd"
import * as LedgerApi from "@/api/ledger"
import { useAppDispatch } from "@/hooks/store"
import { setLedgers } from "@/store/ledger-slice"

type JoinLedgerForm = {
  ledgerId: string
}

interface JoinLedgerModalProps {
  open: boolean
  onClose: () => void
}

export const JoinLedgerDialogue = ({ open, onClose }: JoinLedgerModalProps) => {
  const [form] = Form.useForm()
  const dispatch = useAppDispatch()

  const handleJoinLedger = async (values: JoinLedgerForm) => {
    try {
      await LedgerApi.joinLedger(values.ledgerId)
      const ledgerData = await LedgerApi.getLedgers()
      dispatch(setLedgers(ledgerData))
      message.success("成功加入账本")
      onClose()
      form.resetFields()
    } catch (error) {
      message.error(
        error instanceof AxiosError
          ? error.response?.data.message
          : "加入账本失败"
      )
    }
  }

  return (
    <Modal title="加入账本" open={open} onCancel={onClose} footer={null}>
      <Form<JoinLedgerForm>
        form={form}
        onFinish={handleJoinLedger}
        layout="vertical">
        <Form.Item<JoinLedgerForm>
          name="ledgerId"
          label="账本 ID"
          rules={[{ required: true, message: "请输入账本 ID" }]}>
          <Input />
        </Form.Item>
        <div className="flex gap-[8px] justify-end">
          <Button onClick={onClose}>
            取消
          </Button>
          <Button type="primary" htmlType="submit">
            加入账本
          </Button>
        </div>
      </Form>
    </Modal>
  )
}

// clear-ledger-web/src/components/join-ledger-dialogue.vue
<template>
  <el-dialog v-model="isDialogueVisible" title="加入账本" width="400">
    <el-form :model="joinLedgerForm" label-width="60">
      <el-form-item label="账本 ID">
        <el-input v-model="joinLedgerForm.ledgerId"></el-input>
      </el-form-item>
    </el-form>
    <template #footer>
      <div>
        <el-button
          type="primary"
          @click="onJoinLedger(joinLedgerForm.ledgerId)">
          提交
        </el-button>
        <el-button type="danger" @click="onCancel">取消</el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref } from "vue"
import * as LedgerApi from "@/api/ledger"
import { useLedgerStore } from "@/store"
import { AxiosError } from "axios"
import { ElMessage } from "element-plus"
import { CommonErrorResponse } from "@/types"

const ledgerStore = useLedgerStore()

const isDialogueVisible = defineModel<boolean>({
  required: true,
})

const joinLedgerForm = ref<{
  ledgerId: string
}>({
  ledgerId: "",
})

const closeDialogue = () => {
  isDialogueVisible.value = false
}

const onJoinLedger = (ledgerId: string) => {
  LedgerApi.joinLedger(ledgerId)
    .then((ledger) => {
      ledgerStore.ledgers[ledger.id] = ledger
      ElMessage.success(`恭喜您已成功加入账本 ${ledger.name}`)
    })
    .catch((error) => {
      if (error instanceof AxiosError) {
        const { data }: { data: CommonErrorResponse } = error.response!
        ElMessage.error(data.message)
      } else {
        ElMessage.error("未知错误，请稍后再试")
      }
    })
  closeDialogue()
}

const onCancel = () => {
  joinLedgerForm.value.ledgerId = ""
  closeDialogue()
}
</script>

<style scoped lang="less"></style>
