// clear-ledger-web/src/components/create-ledger-dialogue.vue
<template>
  <el-dialog v-model="isDialogueVisible" title="加入账本" width="400">
    <el-form :model="createLedgerForm" label-width="80">
      <el-form-item label="账本名称">
        <el-input v-model="createLedgerForm.name"></el-input>
      </el-form-item>
      <el-form-item label="账本描述">
        <el-input
          type="textarea"
          :rows="1"
          autosize
          v-model="createLedgerForm.description" />
      </el-form-item>
    </el-form>
    <template #footer>
      <div>
        <el-button type="primary" @click="onCreateLedger(createLedgerForm)">
          提交
        </el-button>
        <el-button type="danger" @click="onCancel">取消</el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref } from "vue"
import { CommonErrorResponse, CreateLedgerRequest } from "@/types"
import * as LedgerApi from "@/api/ledger"
import { useLedgerStore } from "@/store"
import { AxiosError } from "axios"
import { ElMessage, ElNotification } from "element-plus"

const ledgerStore = useLedgerStore()

const isDialogueVisible = defineModel<boolean>()

const createLedgerForm = ref<CreateLedgerRequest>({
  name: "",
  description: "",
})

const closeDialogue = () => {
  isDialogueVisible.value = false
}

const clearData = () => {
  createLedgerForm.value.name = ""
  createLedgerForm.value.description = ""
}

const onCreateLedger = (request: CreateLedgerRequest) => {
  LedgerApi.createLedger(request)
    .then((ledger) => {
      ledgerStore.ledgers.push(ledger)
      ElNotification.success({
        title: "账本创建成功！",
        message: `恭喜你成功创建账本 ${ledger.name}，ID 为 ${ledger.id} ，快邀请他人来加入吧！`,
        duration: 0
      })
    })
    .catch((error) => {
      if (error instanceof AxiosError) {
        const { data }: { data: CommonErrorResponse } = error.response!
        ElMessage.error(data.message)
      } else {
        ElMessage.error("发生未知错误，请稍后再试")
      }
    })
    .then(() => {
      clearData()
      closeDialogue()
    })
}

const onCancel = () => {
  clearData()
  closeDialogue()
}
</script>

<style scoped lang="less"></style>

// clear-ledger-web/src/components/create-ledger-dialogue/index.tsx
import { AxiosError } from "axios"
import { Button, Form, Input, Modal, message } from "antd"
import { useAppDispatch } from "@/hooks/store"
import * as LedgerApi from "@/api/ledger"
import { setLedgers } from "@/store/ledger-slice"
import { CreateLedgerRequest } from "@/types"
import "./index.scss"

interface CreateLedgerDialogueProps {
  open: boolean
  onClose: () => void
}

export const CreateLedgerDialogue = ({
  open,
  onClose,
}: CreateLedgerDialogueProps) => {
  const [form] = Form.useForm()
  const dispatch = useAppDispatch()

  const handleCreateLedger = async (values: CreateLedgerRequest) => {
    try {
      await LedgerApi.createLedger(values)
      const ledgerData = await LedgerApi.getLedgers()
      dispatch(setLedgers(ledgerData))
      message.success("成功创建账本")
      onClose()
      form.resetFields()
    } catch (error) {
      message.error(
        error instanceof AxiosError
          ? error.response?.data.message
          : "创建账本失败"
      )
    }
  }

  return (
    <Modal title="创建账本" open={open} onCancel={onClose} footer={null}>
      <Form<CreateLedgerRequest>
        form={form}
        onFinish={handleCreateLedger}
        layout="vertical">
        <Form.Item<CreateLedgerRequest>
          name="name"
          label="账本名称"
          rules={[{ required: true, message: "请输入账本名称" }]}>
          <Input />
        </Form.Item>
        <Form.Item<CreateLedgerRequest> name="description" label="账本描述">
          <Input.TextArea />
        </Form.Item>
        <div className="create-ledger-controls">
          <Button onClick={onClose}>
            取消
          </Button>
          <Button type="primary" htmlType="submit">
            创建账本
          </Button>
        </div>
      </Form>
    </Modal>
  )
}
